# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: JDK 17 / Setup
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    #- name: Gradle / Validate wrapper
    #  uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    
    #- name: Grant Permissions to gradlew
    #  run: chmod +x gradlew

    - name: Gradle / Setup
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4.2
      
    - name: Gradle / Task (Build)
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4.2
        arguments: build

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4.2
        arguments: publishGprPublicationToGitHubPackagesRepository --stacktrace
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PACKAGES_UPLOAD_TOKEN: ${{ secrets.PUBLISH_NOEXPIRE_TOKEN }}
